/**
 * Footer Component
 *
 * Application footer with theme/screenset controls.
 * Generated by `frontx scaffold layout`.
 */

import React from 'react';
import { useAppSelector, type FooterState } from '@gears-frontx/react';

export interface FooterProps {
  children?: React.ReactNode;
}

export const Footer: React.FC<FooterProps> = ({ children }) => {
  const footerState = useAppSelector((state) => state['layout/footer'] as FooterState | undefined);
  const visible = footerState?.visible ?? true;

  // The strip is a container and carries nothing of its own, so with no
  // children it renders a 40px band of border and background across the whole
  // viewport that no screen can fill: `Layout` passes it none, and the layout
  // plugin exposes no footer event a microfrontend could hide it with. Absence
  // of children is therefore the only signal available, and it is the right
  // one - `visible` stays the explicit switch for a footer that does have
  // content.
  // `Children.count` treats a falsy conditional child (`{enabled &&
  // <FooterContent />}` with `enabled` false) as one slot, not zero, so it
  // would let the empty band this check exists to suppress back in the
  // moment a caller writes the pattern. `Children.toArray` drops those slots
  // before counting.
  if (!visible || React.Children.toArray(children).length === 0) {
    return null;
  }

  return (
    <footer className="h-10 flex items-center justify-between px-4 border-t border-border bg-background">
      {children}
    </footer>
  );
};

Footer.displayName = 'Footer';
