/**
 * MFE Bootstrap
 *
 * Registers MFE domains, extensions, and handlers with the FrontX app.
 * Initial screen mounting is owned by ExtensionDomainSlot once its container
 * ref is attached.
 * This file is imported in main.tsx to wire MFE capabilities into the host app.
 *
 * MFE manifests are auto-generated by the `generate:mfe-manifests` script into
 * ./generated-mfe-manifests. Re-run it after adding or removing MFE packages
 * from src/mfe_packages/ with your package manager, for example
 * `npm run generate:mfe-manifests`, `yarn generate:mfe-manifests`, or
 * `pnpm generate:mfe-manifests`.
 */

import type { RefObject } from 'react';
import {
  ExtensionDomainImplementation,
  ExtensionDomainImplementationFactory,
  ExclusiveMountStrategy,
  OptionalMountStrategy,
  ActionHandler,
  HAI3_ACTION_MOUNT_EXT,
  HAI3_ACTION_UNMOUNT_EXT,
  HAI3_SHARED_PROPERTY_THEME,
  HAI3_SHARED_PROPERTY_LANGUAGE,
  screenDomain,
  sidebarDomain,
  popupDomain,
  overlayDomain,
} from '@cyberfabric/react';
import type {
  HAI3App,
  Extension,
  ScreenExtension,
  MfeRegistry,
  ContainerHooks,
  DomainContext,
  ActionPayload,
  MountStrategy,
} from '@cyberfabric/react';
import { MFE_MANIFESTS, type MfeManifestConfig } from './generated-mfe-manifests.ts';

// ─── Domain implementation building blocks ───────────────────────────────────
//
// Each domain registered with the registry pairs an ExtensionDomain declaration
// with an ExtensionDomainImplementationFactory whose build(ctx) constructs an
// ExtensionDomainImplementation. The implementation captures the per-domain
// mounter and a ContainerHooks inside its chosen MountStrategy and registers
// per-action-type handlers that delegate to the strategy.

class HostContainerHooks implements ContainerHooks {
  private readonly elements = new Map<string, HTMLElement>();

  create(extensionId: string): Element {
    const el = document.createElement('div');
    el.dataset.extensionId = extensionId;
    el.style.height = '100%';
    this.elements.set(extensionId, el);
    return el;
  }

  destroy(extensionId: string): void {
    this.elements.delete(extensionId);
  }
}

class ScreenDomainImpl extends ExtensionDomainImplementation {
  private readonly strategy: ExclusiveMountStrategy;

  constructor(ctx: DomainContext, hooks: ContainerHooks, registry: MfeRegistry, domainId: string) {
    super();
    this.strategy = new ExclusiveMountStrategy(ctx.mounter, hooks, registry, domainId);
    ctx.registerHandler(
      HAI3_ACTION_MOUNT_EXT,
      ActionHandler.fromFunction((_t, p) => this.strategy.mount(p as ActionPayload)),
    );
  }

  protected getMountStrategies(): MountStrategy[] {
    return [this.strategy];
  }
}

class OptionalDomainImpl extends ExtensionDomainImplementation {
  private readonly strategy: OptionalMountStrategy;

  constructor(ctx: DomainContext, hooks: ContainerHooks, registry: MfeRegistry, domainId: string) {
    super();
    this.strategy = new OptionalMountStrategy(ctx.mounter, hooks, registry, domainId);
    ctx.registerHandler(
      HAI3_ACTION_MOUNT_EXT,
      ActionHandler.fromFunction((_t, p) => this.strategy.mount(p as ActionPayload)),
    );
    ctx.registerHandler(
      HAI3_ACTION_UNMOUNT_EXT,
      ActionHandler.fromFunction((_t, p) => this.strategy.unmount!(p as ActionPayload)),
    );
  }

  protected getMountStrategies(): MountStrategy[] {
    return [this.strategy];
  }
}

class ScreenDomainFactory extends ExtensionDomainImplementationFactory {
  constructor(private readonly registry: MfeRegistry) { super(); }
  build(ctx: DomainContext): ScreenDomainImpl {
    return new ScreenDomainImpl(ctx, new HostContainerHooks(), this.registry, screenDomain.id);
  }
}

class OptionalDomainFactory extends ExtensionDomainImplementationFactory {
  constructor(
    private readonly registry: MfeRegistry,
    private readonly domainId: string,
  ) { super(); }
  build(ctx: DomainContext): OptionalDomainImpl {
    return new OptionalDomainImpl(ctx, new HostContainerHooks(), this.registry, this.domainId);
  }
}

function isScreenExtension(extension: Extension): extension is ScreenExtension {
  const candidate = extension as { presentation?: { route?: string } };
  return typeof candidate.presentation?.route === 'string';
}

/**
 * Bootstrap MFE system for the host application.
 * Registers domains, extensions, and shared properties.
 * Initial screen mount is deferred to MfeScreenContainer -> ExtensionDomainSlot.
 *
 * @param app - FrontX application instance
 * @param screenContainerRef - React ref for the screen domain container element (reserved for future slot wiring)
 * @returns Array of registered screen extensions, for URL routing in MfeScreenContainer
 */
export async function bootstrapMFE(
  app: HAI3App,
  // screenContainerRef is kept for API compatibility; slot wiring is owned by ExtensionDomainSlot
  _screenContainerRef?: RefObject<HTMLDivElement | null>,
): Promise<ScreenExtension[]> {
  const registry = app.mfeRegistry;
  if (!registry) {
    throw new Error('[MFE Bootstrap] mfeRegistry is not available on app instance');
  }

  registry.registerDomain(screenDomain, new ScreenDomainFactory(registry));
  registry.registerDomain(sidebarDomain, new OptionalDomainFactory(registry, sidebarDomain.id));
  registry.registerDomain(popupDomain, new OptionalDomainFactory(registry, popupDomain.id));
  registry.registerDomain(overlayDomain, new OptionalDomainFactory(registry, overlayDomain.id));

  const currentThemeId = app.themeRegistry?.getCurrent()?.id ?? 'default';
  registry.updateSharedProperty(HAI3_SHARED_PROPERTY_THEME, currentThemeId);
  const derivedLanguage = app.i18nRegistry.getLanguage() ?? 'en';
  registry.updateSharedProperty(HAI3_SHARED_PROPERTY_LANGUAGE, derivedLanguage);

  if (MFE_MANIFESTS.length === 0) {
    console.warn(
      '[MFE Bootstrap] No MFE manifests found. From the project root, run `generate:mfe-manifests` with your package manager, for example `npm run generate:mfe-manifests`, `yarn generate:mfe-manifests`, or `pnpm generate:mfe-manifests`.',
    );
    return [];
  }

  const manifests = MFE_MANIFESTS as MfeManifestConfig[];
  const screenExtensions: ScreenExtension[] = [];

  for (const config of manifests) {
    // Register MFE-carried schemas (custom actions, properties) before entries so the
    // type system can validate entry references to these schemas at registration time.
    if (config.schemas) {
      for (const schema of config.schemas) {
        registry.typeSystem.registerSchema(schema);
      }
    }

    registry.typeSystem.register(config.manifest);

    for (const entry of config.entries) {
      registry.typeSystem.register({ ...entry, manifest: config.manifest });
    }

    for (const extension of config.extensions) {
      await registry.registerExtension(extension);
    }

    screenExtensions.push(...config.extensions.filter(isScreenExtension));
  }

  if (screenExtensions.length === 0) {
    console.warn('[MFE Bootstrap] No screen extensions available, skipping mount');
    return [];
  }

  return screenExtensions;
}
